<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:25:46.
 */
Prado::using("Application.common.string");
class BrandRecord extends TActiveRecord
{
	const TABLE='tbl_brand';

	public $ID;
	public $Alias;
	public $Name;
	
	public static $COLUMN_MAPPING=array
	(
		'brand_id'=>'ID',
		'brand_alias'=>'Alias',
		'brand_name'=>'Name'
	);
	
	public static $RELATIONS=array
	(
		'Products'=>array(self::HAS_MANY,'ProductRecord','brand_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public function save()
	{
		$this->Alias = String::removeAccents(strlen($this->Alias) > 0 ? $this->Alias : $this->Name);
		parent::save();
	}
}
?>