<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:55:26.
 */
class cartTempRecord extends TActiveRecord
{
	const TABLE='tbl_cart_temp';

	public $session_id;
	public $user_id;
	public $billing_id;
	public $shipping_id;
	public $subtotal;
	public $shipping_method_id;
	public $shipping_amount;
	public $coupon_code;
	public $coupon_amount;
	public $tax_amount;
	public $c_date;
	
	public static $COLUMN_MAPPING=array
	(
		
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>