<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:55:47.
 */
class CartTempDetailRecord extends TActiveRecord
{
	const TABLE='tbl_cart_temp_detail';

	public $SessionID;
	public $UserID;
	public $ProductID;
	public $UnitPrice;
	public $Quantity;
	public $Subtotal;
	public $CreateDate;
	
	public static $COLUMN_MAPPING=array
	(
		'session_id'=>'SessionID',
		'user_id'=>'UserID',
		'product_id'=>'ProductID',
		'unit_price'=>'UnitPrice',
		'quantity'=>'Quantity',
		'subtotal'=>'Subtotal',
		'c_date'=>'CreateDate'
	);
	
	public static $RELATIONS=array
	(
		'User'=>array(self::BELONGS_TO,'UserRecord','user_id'),
		'Product'=>array(self::BELONGS_TO,'ProductRecord','product_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>