<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:56:16.
 */
class countryRecord extends TActiveRecord
{
	const TABLE='tbl_country';

	public $ID;
	public $Code;
	public $Name;
	
	public static $COLUMN_MAPPING=array
	(
		'country_id'=>'ID',
		'country_code'=>'Code',
		'country_name'=>'Name'
	);
	
	public static $RELATIONS=array
	(
		'Addresses'=>array(self::HAS_MANY,'UserAddressRecord','country_code')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>