<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:29:08.
 */
class MailingListRecord extends TActiveRecord
{
	const TABLE='tbl_mailing_list';

	public $ID;
	public $Address;
	public $UserID;
	
	public static $COLUMN_MAPPING=array
	(
		'mailing_id'=>'ID',
		'mailing_address'=>'Address',
		'user_id'=>'UserID'
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>