<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:30:05.
 */
class OrderItemRecord extends TActiveRecord
{
	const TABLE='tbl_order_item';

	public $ID;
	public $OrderID;
	public $ProductID;
	public $Quantity;
	public $UnitPrice;
	public $Subtotal;
	public $CreateDate;
	public $ModifyDate;
	
	public static $COLUMN_MAPPING=array
	(
		'item_id'=>'ID',
		'order_id'=>'OrderID',
		'product_id'=>'ProductID',
		'quantity'=>'Quantity',
		'unit_price'=>'UnitPrice',
		'subtotal'=>'Subtotal',
		'c_date'=>'CreateDate',
		'm_date'=>'ModifyDate'
	);
	
	public static $RELATIONS=array
	(
		'Order'=>array(self::BELONGS_TO,'OrderRecord','order_id'),
		'Product'=>array(self::BELONGS_TO,'ProductRecord','product_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>