<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:30:05.
 */
class OrderItemRecord extends TActiveRecord
{
	const TABLE='tbl_order_item';

	public $ID;
	public $OrderID;
	public $ProductID;
	public $PropertyID;
	public $DiscountName;
	public $DiscountAmount;
	public $DiscountIsPercent;
	public $UnitPrice;
	public $Quantity;
	public $Subtotal;
	public $Counter;
	public $CreateDate;
	public $ModifyDate;
	
	public static $COLUMN_MAPPING=array
	(
		'item_id'=>'ID',
		'order_id'=>'OrderID',
		'product_id'=>'ProductID',
		'prop_id'=>'PropertyID',
		'discount_name'=>'DiscountName',
		'discount_amount'=>'DiscountAmount',
		'discount_is_percent'=>'DiscountIsPercent',
		'unit_price'=>'UnitPrice',
		'quantity'=>'Quantity',
		'subtotal'=>'Subtotal',
		'gen_counter'=>'Counter',
		'c_date'=>'CreateDate',
		'm_date'=>'ModifyDate'
	);
	
	public static $RELATIONS=array
	(
		'Order'=>array(self::BELONGS_TO,'OrderRecord','order_id'),
		'Product'=>array(self::BELONGS_TO,'ProductRecord','product_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public function save()
	{
		if ($this->ID<=0)
		{
			$this->CreateDate = time();
		}
		$this->ModifyDate = time();
		parent::save();
	}
	
	protected function getProperty()
	{
		return PropertyRecord::finder()->withProduct()->findByPk($this->PropertyID);
	}
}
?>