<?php
/**
 * Auto generated by prado-cli.php on 2010-01-02 09:18:10.
 */
class PackageTypeMethod extends TActiveRecord
{
	const TABLE='tbl_product_package';

	public $ID;
	public $ProductID;
	public $Unit;
	public $UOM;
	public $Price;
	public $InStock;
	
	public static $COLUMNS_MAPPING=array
	(
		'package_id'=>'ID',
		'product_id'=>'ProductID',
		'package_unit'=>'Unit',
		'package_uom'=>'UOM',
		'package_price'=>'Price',
		'package_in_stock'=>'InStock'
	);
	
	public static $RELATIONS=array
	(
		'Product'=>array(self::BELONGS_TO,'ProductRecord','product_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>