<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:30:52.
 */
class PaymentMethodRecord extends TActiveRecord
{
	const TABLE='tbl_payment_method';

	public $ID;
	public $Alias;
	public $Name;
	public $IsPublished;
	public $ImagePath;
	
	public static $COLUMN_MAPPING=array
	(
		'method_id'=>'ID',
		'method_alias'=>'Alias',
		'method_name'=>'Name',
		'method_publish'=>'IsPublished',
		'method_image'=>'ImagePath'
		
	);
	
	public static $RELATIONS=array
	(
		'Payments'=>array(self::HAS_MANY,'PaymentRecord','method_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public function save()
	{
		$this->Alias = String::removeAccents(strlen($this->Alias) > 0 ? $this->Alias : $this->Name);
		parent::save();
	}
	
	public function getAllItems($publishedOnly=false)
	{
		$criteria = new TActiveRecordCriteria;
		$criteria->Condition = "method_id > 0";
		if ($publishedOnly) $criteria->Condition .= " and method_publish = 1";
		$criteria->OrdersBy["method_id"] = "asc";
		return self::finder()->findAll($criteria);
	}
}
?>