<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:30:08.
 */
class productRecord extends TActiveRecord
{
	const TABLE='tbl_product';

	public $ID;
	public $mfID;
	public $brandID;
	public $discountID;
	public $SKU;
	public $Name;
	public $Brief;
	public $Description;
	public $Image;
	public $Thumbnail;
	public $Price;
	public $rewardPoints;
	public $isBestSeller;
	public $isHotDeal;
	public $isNewArrival;
	public $isPublished;
	public $Ordering;
	public $inStock;
	public $UOM;
	public $availableDate;
	public $createDate;
	public $updateDate;
	
	public static $COLUMN_MAPPING=array
	(
		'product_id'=>'ID',
		'mf_id'=>'mfID',
		'brand_id'=>'brandID',
		'discount_id'=>'discountID',
		'product_sku'=>'SKU',
		'product_name'=>'Name',
		'product_brief'=>'Brief',
		'product_desc'=>'Description',
		'product_image'=>'Image',
		'product_thumb'=>'Thumbnail',
		'product_price'=>'Price',
		'product_reward_points'=>'rewardPoints',
		'product_best_seller'=>'isBestSeller',
		'product_hot_deal'=>'isHotDeal',
		'product_new_arrival'=>'isNewArrival',
		'product_publish'=>'isPublished',
		'product_order'=>'Ordering',
		'product_in_stock'=>'inStock',
		'product_uom'=>'UOM',
		'product_available_date'=>'availableDate',
		'c_date'=>'createDate',
		'm_date'=>'updateDate'
	);
	
	public static $RELATIONS=array
	(
		'Brand'=>array(self::BELONGS_TO,'brandRecord','brand_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>