<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:31:37.
 */
class ProductCatRecord extends TActiveRecord
{
	const TABLE='tbl_product_cat_xref';

	public $ProductID;
	public $CatID;
	
	public static $COLUMN_MAPPING=array
	(
		'product_id'=>'ProductID',
		'cat_id'=>'CatID'
	);
	
	public static $RELATIONS=array
	(
		'Product'=>array(self::BELONGS_TO,'ProductRecord','product_id'),
		'Category'=>array(self::BELONGS_TO,'CategoryRecord','cat_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>