<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:32:58.
 */
class UserTypeRecord extends TActiveRecord
{
	const TABLE='tbl_user_type';

	public $ID;
	public $Alias;
	public $Name;

	public static $COLUMN_MAPPING=array
	(
		'user_type_id'=>'ID',
		'user_type_alias'=>'Alias',
		'user_type_name'=>'Name'
	);
	
	public static $RELATIONS=array
	(
		'Users'=>array(self::HAS_MANY,'UserRecord','user_type_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>