<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:55:47.
 */
class CartTempDetailRecord extends TActiveRecord
{
	const TABLE='tbl_cart_temp_detail';

	public $HashID;
	public $SessionID="";
	public $UserID=0;
	public $ProductID=0;
	public $PropertyID=0;
	public $Quantity=0;
	public $Subtotal=0;
	public $CreateDate=0;
	
	public static $COLUMN_MAPPING=array
	(
		'hash_id'=>'HashID',
		'session_id'=>'SessionID',
		'user_id'=>'UserID',
		'product_id'=>'ProductID',
		'prop_id'=>'PropertyID',
		'quantity'=>'Quantity',
		'subtotal'=>'Subtotal',
		'c_date'=>'CreateDate'
	);
	
	public static $RELATIONS=array
	(
		'User'=>array(self::BELONGS_TO,'UserRecord','user_id'),
		'Product'=>array(self::BELONGS_TO,'ProductRecord','product_id'),
		'CartTemp'=>array(self::BELONGS_TO,'CartTempRecord','session_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	protected function getProperty()
	{
		return PropertyRecord::finder()->findByPk($this->PropertyID);
	}
}
?>