<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:55:47.
 */
class cartTempDetailRecord extends TActiveRecord
{
	const TABLE='tbl_cart_temp_detail';

	public $sessionID;
	public $userID;
	public $productID;
	public $unitPrice;
	public $Quantity;
	public $Subtotal;
	public $createDate;
	
	public static $COLUMN_MAPPING=array
	(
		'session_id'=>'sessionID',
		'user_id'=>'userID',
		'product_id'=>'productID',
		'unit_price'=>'unitPrice',
		'quantity'=>'Quantity',
		'subtotal'=>'Subtotal',
		'c_date'=>'createDate'
	);
	
	public static $RELATIONS=array
	(
		'User'=>array(self::BELONGS_TO,'userRecord','user_id'),
		'Product'=>array(self::BELONGS_TO,'productRecord','product_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>