<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:56:05.
 */
class categoryRecord extends TActiveRecord
{
	const TABLE='tbl_category';

	public $cat_id;
	public $parent_id;
	public $cat_name;
	public $cat_alias;
	public $cat_desc;
	public $cat_image;
	public $cat_thumb;
	public $cat_publish;
	public $cat_order;
	public $cat_frontpage;
	public $c_date;
	public $m_date;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>