<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:56:05.
 */
class CategoryRecord extends TActiveRecord
{
	const TABLE='tbl_category';

	public $ID;
	public $ParentID;
	public $Name;
	public $Alias;
	public $Description;
	public $ImagePath;
	public $ThumbnailPath;
	public $IsPublished;
	public $Ordering;
	public $IsFrontPage;
	public $CreateDate;
	public $ModifyDate;
	
	public static $COLUMN_MAPPING=array
	(
		'cat_id'=>'ID',
		'parent_id'=>'ParentID',
		'cat_name'=>'Name',
		'cat_alias'=>'Alias',
		'cat_desc'=>'Description',
		'cat_image'=>'ImagePath',
		'cat_thumb'=>'ThumbnailPath',
		'cat_publish'=>'IsPublished',
		'cat_order'=>'Ordering',
		'cat_frontpage'=>'IsFrontPage',
		'c_date'=>'CreateDate',
		'm_date'=>'ModifyDate'
	);
	
	public static $RELATIONS=array
	(
		'Parent'=>array(self::BELONGS_TO, 'CategoryRecord', 'parent_id'),
		'Childs'=>array(self::HAS_MANY, 'CategoryRecord', 'parent_id'),
		'Products'=>array(self::MANY_TO_MANY, 'ProductRecord', 'tbl_product_cat_xref')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>