<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:56:16.
 */
class countryRecord extends TActiveRecord
{
	const TABLE='tbl_country';

	public $country_id;
	public $country_code;
	public $country_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>