<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:28:48.
 */
class CouponRecord extends TActiveRecord
{
	const TABLE='tbl_coupon';

	public $ID;
	public $Code;
	public $IsPercent;
	public $IsPublished;
	public $Amount;
	
	public static $COLUMN_MAPPING=array
	(
		'coupon_id'=>'ID',
		'coupon_code'=>'Code',
		'coupon_amount'=>'Amount',
		'coupon_publish'=>'IsPublished',
		'is_percent'=>'IsPercent'
	);
	
	public static $RELATIONS=array
	(
		'Orders'=>array(self::HAS_MANY,'OrderRecord','coupon_code')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public function getAllItems()
	{
		$criteria = new TActiveRecordCriteria;
		$criteria->Condition = "coupon_id > 0 and coupon_publish = 1";
		$criteria->OrdersBy["coupon_code"] = "asc";
		return self::finder()->findAll($criteria);
	}
}
?>