<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:31:54.
 */
class DiscountRecord extends TActiveRecord
{
	const TABLE='tbl_product_discount';

	public $ID;
	public $Name;
	public $Amount;
	public $IsPercent;
	public $StartDate;
	public $EndDate;
	
	public static $COLUMN_MAPPING=array
	(
		'discount_id'=>'ID',
		'discount_name'=>'Name',
		'discount_amount'=>'Amount',
		'is_percent'=>'IsPercent',
		's_date'=>'StartDate',
		'e_date'=>'EndDate',
	);
	
	public static $RELATIONS=array
	(
		'Products'=>array(self::HAS_MANY,'ProductRecord','discount_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>