<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:29:24.
 */
class ManufacturerRecord extends TActiveRecord
{
	const TABLE='tbl_manufacturer';

	public $ID;
	public $Name;
	public $mf_desc;
	public $Email;
	public $Url;
	
	public static $COLUMN_MAPPING=array
	(
		'mf_id'=>'ID',
		'mf_name'=>'Name',
		'mf_email'=>'Email',
		'mf_url'=>'Url'
	);
	
	public static $RELATIONS=array
	(
		'Products'=>array(self::HAS_MANY,'ProductRecord','mf_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>