<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:30:24.
 */
class OrderStatusRecord extends TActiveRecord
{
	const TABLE='tbl_order_status';

	public $ID;
	public $Alias;
	public $Code;
	public $Name;
	public $Description;
	
	public static $COLUMN_MAPPING=array
	(
		'status_id'=>'ID',
		'status_alias'=>'Alias',
		'status_code'=>'Code',
		'status_name'=>'Name',
		'status_desc'=>'Description'
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public function save()
	{
		$this->Alias = String::removeAccents(strlen($this->Alias) > 0 ? $this->Alias : $this->Name);
		parent::save();
	}
}
?>