<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:30:52.
 */
class PaymentMethodRecord extends TActiveRecord
{
	const TABLE='tbl_payment_method';

	public $ID;
	public $Alias;
	public $Name;
	public $IsPublished;
	
	public static $COLUMN_MAPPING=array
	(
		'method_id'=>'ID',
		'method_alias'=>'Alias',
		'method_name'=>'Name',
		'method_publish'=>'IsPublished'
	);
	
	public static $RELATIONS=array
	(
		'Payments'=>array(self::HAS_MANY,'PaymentRecord','method_id')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>