<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:30:08.
 */
class ProductRecord extends TActiveRecord
{
	const TABLE='tbl_product';

	public $ID;
	public $MFID;
	public $BrandID;
	public $DiscountID;
	public $Alias;
	public $SKU;
	public $Name;
	public $Brief;
	public $Description;
	public $Image;
	public $Thumbnail;
	public $Price;
	public $RewardPoints;
	public $IsBestSeller;
	public $IsHotDeal;
	public $IsNewArrival;
	public $IsPublished;
	public $Ordering;
	public $InStock;
	public $UOM;
	public $AvailableDate;
	public $CreateDate;
	public $ModifyDate;
	
	public static $COLUMN_MAPPING=array
	(
		'product_id'=>'ID',
		'mf_id'=>'MFID',
		'brand_id'=>'BrandID',
		'discount_id'=>'DiscountID',
		'product_sku'=>'SKU',
		'product_alias'=>'Alias',
		'product_name'=>'Name',
		'product_brief'=>'Brief',
		'product_desc'=>'Description',
		'product_image'=>'Image',
		'product_thumb'=>'Thumbnail',
		'product_price'=>'Price',
		'product_reward_points'=>'RewardPoints',
		'product_best_seller'=>'IsBestSeller',
		'product_hot_deal'=>'IsHotDeal',
		'product_new_arrival'=>'IsNewArrival',
		'product_publish'=>'IsPublished',
		'product_order'=>'Ordering',
		'product_in_stock'=>'InStock',
		'product_uom'=>'UOM',
		'product_available_date'=>'AvailableDate',
		'c_date'=>'CreateDate',
		'm_date'=>'ModifyDate'
	);
	
	public static $RELATIONS=array
	(
		'Brand'=>array(self::BELONGS_TO,'BrandRecord','brand_id'),
		'Manufacturer'=>array(self::BELONGS_TO,'ManufacturerRecord','mf_id'),
		'Discount'=>array(self::BELONGS_TO,'DiscountRecord','discount_id'),
		'Categories'=>array(self::MANY_TO_MANY,'CategoryRecord','tbl_product_cat_xref')
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>