<?php
/**
 * Auto generated by prado-cli.php on 2009-12-09 09:30:08.
 */
Prado::using("Application.common.string");
class SpecialOfferRecord extends TActiveRecord
{
	const TABLE='tbl_special_offer';

	public $ID;
	public $Title;
	public $Alias;	
	public $Content;
	public $Link;
	public $ImagePath;
	public $IsPublished;
	public $Ordering;
	public $CreateDate;
	public $ModifyDate;
	
	public static $COLUMN_MAPPING=array
	(
		'special_offer_id'=>'ID',
		'offer_title'=>'Title',
		'offer_alias'=>'Alias',
		'offer_content'=>'Content',
		'offer_link'=>'Link',
		'offer_image'=>'ImagePath',
		'offer_publish'=>'IsPublished',
		'offer_order'=>'Ordering',
		'c_date'=>'CreateDate',
		'm_date'=>'ModifyDate'
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
		
	public function save()
	{
		if ($this->ID <= 0)
		{
			$criteria = new TActiveRecordCriteria;
			$criteria->Condition = "special_offer_id <> 0";
			$this->Ordering = self::finder()->count($criteria)+1;
			$this->CreateDate = time();
		}
		$this->Alias = String::removeAccents(strlen($this->Alias) > 0 ? $this->Alias : $this->Title);
		$this->ModifyDate = time();
		parent::save();
	}
	
	public function getAllItems($publishedOnly=false)
	{
		$criteria = new TActiveRecordCriteria;
		$criteria->Condition = "special_offer_id > 0";
		if ($publishedOnly) $criteria->Condition .= " and offer_publish = 1";
		return self::finder()->findAll($criteria);
	}
}
?>